# FROM ubuntu:22.04
FROM node:17
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install libwebkit2gtk-4.0-dev \
  build-essential \
  curl \
  wget \
  libssl-dev \
  libgtk-3-dev \
  librsvg2-dev \
  -y

  # libappindicator3-dev \
# RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
# RUN nvm install node --latest-npm && \
#   nvm use node 
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -y | sh 
WORKDIR /usr/src/app/2/desktop
