name: "Bundle app"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-web:
    uses: utkusarioglu/web/.github/workflows/build-web.yml@main

  publish-tauri:
    needs: build-web
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    env:
      NODE_ENV: production
    steps:
      - name: Checkout desktop
        uses: actions/checkout@v3
        with:
          path: desktop
      - name: Download web build artifact
        uses: actions/download-artifact@v2
        with:
          name: utkusarioglu-web-build
          path: web/build

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 17
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # - name: install dependencies (ubuntu only)
      #   if: matrix.platform == 'ubuntu-latest'
      #   working-directory: desktop
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      
      - name: Install desktop dependencies
        working-directory: desktop
        run: |
          yarn install --network-timeout 1000000 --frozen-lockfile --production false
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: desktop
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
      - name: Builds as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: desktop/src-tauri/target/release/bundle
